version: '3.9'

services:
  neo4j:
    image: neo4j:latest

    container_name: graph-db

    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/password

    ports:
      - 7474:7474
      - 7687:7687

    volumes:
      - ./neo4j/data:/neo4j/data
      - ./neo4j/logs:/neo4j/logs
      - ./neo4j/import:/var/lib/neo4j/import

    restart: unless-stopped
